# Generated by Django 3.2.5 on 2021-07-31 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
