# Generated by Django 3.2.6 on 2021-08-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseason',
            name='permission_type',
            field=models.CharField(choices=[('admin', 'admin'), ('referee', 'referee')], default='referee', max_length=10),
        ),
    ]
