# Generated by Django 4.0.3 on 2022-03-31 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organization_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/%Y/%m/"),
        ),
    ]
