# Generated by Django 4.0.3 on 2022-04-04 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_game"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="start_date",
        ),
    ]
