version: "3.9"

services:
  users-service:
    build:
      context: ../server/users
      dockerfile: Dockerfile
    volumes:
      - ../server/users:/code
    depends_on:
      - users-postgres-service
  users-postgres-service:
    image: postgres
    volumes:
      - users-database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  organizations-service:
    build:
      context: ../server/organizations
      dockerfile: Dockerfile
    volumes:
      - ../server/organizations:/code
    depends_on:
      - organizations-postgres-service
  organizations-postgres-service:
    image: postgres
    volumes:
      - organizations-database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  gateway-service:
    build:
      context: ../server/gateway
      dockerfile: Dockerfile
    volumes:
      - ../server/gateway:/code
    depends_on:
      - users-service
      - organizations-service
    ports:
      - "4000:4000"
volumes:
  users-database-data: {}
  organizations-database-data: {}
