version: "3.9"

services:
  users-service:
    build:
      context: ../server/users_service
      dockerfile: Dockerfile
    volumes:
      - ../server/users_service:/code
  organizations-service:
    build:
      context: ../server/organizations_service
      dockerfile: Dockerfile
    volumes:
      - ../server/organizations_service:/code
  permits-service:
    build:
      context: ../server/permits_service
      dockerfile: Dockerfile
    volumes:
      - ../server/permits_service:/code
  gateway-service:
    build:
      context: ../server/gateway_service
      dockerfile: Dockerfile
    volumes:
      - ../server/gateway_service:/code
    depends_on:
      - users-service
      - organizations-service
      - permits-service
    ports:
      - "4000:4000"
