apiVersion: skaffold/v2beta13
kind: Config
build:
  local:
    push: false  # disable pushing to docker hub
  artifacts:
    - image: jonathankao97/umpcast-gateway
      context: server/gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/gateway/**"
            dest: .
    - image: jonathankao97/umpcast-users
      context: server/users
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/users/**"
            dest: .
    - image: jonathankao97/umpcast-organizations
      context: server/organizations
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "server/organizations/**"
            dest: .
deploy:
  kubectl:
    manifests:
      - "infra/k8s/**/*.yml"
