version: "3.9"

services:
  permits:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    depends_on:
      - permits-db
    ports:
      - "8000:8000"
  permits-db:
    image: postgres
    volumes:
      - permits-database-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "6543:5432"
volumes:
  permits-database-data: {}