# Generated by Django 4.0.3 on 2022-03-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_city_alter_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pics/%Y/%m/"
            ),
        ),
    ]
