# Generated by Django 4.0.3 on 2022-04-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0002_usergamerole_userrole_userseason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userorganization",
            name="is_member",
        ),
    ]
