name: cdk8s

on:
  pull_request:
    paths:
      - server/cdk8s
      - .github/workflows/cdk8s.yml

jobs:
  build:
   defaults:
      run:
        working-directory: infra/cdk8s
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9    
    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Check Imports using isort
      run: |
        pipenv run isort --check-only --profile black .

    - name: Check Formatting using Black
      run: |
        pipenv run black --check .
