name: client_expo_publish
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/client_expo_publish.yml
defaults:
  run:
    working-directory: client
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/client_setup
        with:
          expo_token: ${{ secrets.EXPO_TOKEN }}
      - name: Publish to production
        run: expo publish --release-channel production
