name: client_test
on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"
      - ".github/workflows/client_test.yml"
jobs:
  build:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/client_setup
      - name: TEST Prettier
        run: yarn prettier --check ./src
      - name: TEST Eslint
        run: yarn eslint --ext .js,.jsx,.ts,.tsx ./src
      - name: TEST Jest
        run: yarn test