name: client_web_deploy
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/client_web_deploy.yml
defaults:
  run:
    working-directory: client
jobs:
  main:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/client_setup
        with:
          expo_token: ${{ secrets.EXPO_TOKEN }}
      - name: Build web app
        run: expo build:web
      - name: Deploy live to Firebase web hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_UMPCAST_PROD }}
          entryPoint: client
          channelId: live
          projectId: umpcast-prod
