name: client_prod_publish
on:
  push:
    branches:
      - main
    paths:
      - client/**
      - .github/workflows/client_prod_publish.yml
defaults:
  run:
    working-directory: client
jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: client/yarn.lock
      
      - name: Setup Expo
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Publish update
        run: eas update --auto --branch production
        env:
          APP_ENV: production