name: client
on:
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/client.yml"
jobs:
  build:
    defaults:
      run:
        working-directory: client
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test