name: client_expo_deploy
on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
      - '.github/workflows/client_expo_publish.yml'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: ./.github/actions/client_setup
      - name: Publish to production
        run: eas build --profile production --auto-submit -p android