name: publish_permits_service

on:
  push:
   branches:
     - main
   paths:
    - server/permits_service
    - .github/workflows/publish_permits_service.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/permits_service

jobs:
  build:
    defaults:
      run:
        working-directory: server/permits_service
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ github.SHA }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: server/permits_service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
