name: server

on:
  pull_request:
    paths:
      - server/**
      - .github/workflows/server.yml

jobs:
  build:
    defaults:
      run:
        working-directory: server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Check Types using MyPy
        run: |
          pipenv run mypy .
        env:
          ENV_NAME: Production
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Check Imports using isort
        run: |
          pipenv run isort --check-only --profile black .

      - name: Check Formatting using Black
        run: |
          pipenv run black --check .
        
      - name: Run Tests
        run: |
          pipenv run python manage.py test
        env:
          ENV_NAME: Production
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Check Coverage
        run: |
          pipenv run coverage run --source='.' manage.py test
          pipenv run coverage report --show-missing --fail-under=50
        env:
          ENV_NAME: Production
          AWS_REGION: ${{secrets.AWS_REGION}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
