name: sync_cdk8s

on: pull_request

jobs:
  build:
   defaults:
      run:
        working-directory: infra/cdk8s
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - run: npm install -g cdk8s-cli

    - name: Create k8s manifests
      run: |
        cdk8s import
        cdk8s synth
      
    - name: Copy k8s manifests to .deploy/
      working-directory: .
      run: |
        cp -a infra/cdk8s/dist/. .deploy/
    
    - name: Commit files
      working-directory: .
      run: |
        git config user.name github-actions
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .deploy/
        git commit -m "ci(cdk8s): update k8s manifests" || exit 0
        git push