name: sync_cdk8s

on:
  push:
   branches:
     - main  

jobs:
  build:
   defaults:
      run:
        working-directory: infra/cdk8s
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install cdk8s
      run: brew install cdk8s

    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Create k8s manifests
      run: |
        cdk8s import
        cdk8s synth
      
    - name: Copy k8s manifests to .deploy/
      working-directory: .
      run: |
        cp -a infra/cdk8s/dist/. .deploy/
    
    - name: Commit files
      working-directory: .
      run: |
        git config user.name github-actions
        git config user.email github-actions[bot]@users.noreply.github.com
        git add .deploy/
        git commit -m "ci(cdk8s): update k8s manifests" || exit 0
        git push --force
